apiVersion: v1
kind: Service
metadata:
  name: {{ include "deis-workflow.fullname" . }}
  labels:
    {{- include "deis-workflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.kafka.port }}
      targetPort: http
      name: kafka
    - port: {{ .Values.helm.registryPort }}
      targetPort: http
      name: helm-registry
